# This is a basic workflow to help you get started with Actions

name: PyTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up -d
    
    - name: install Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Chrome
      run: |
       sudo apt install google-chrome-stable

    - name: Install selenium
      run: pip install selenium

    

       
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
       
    - name: Run Tests
      run: |
        pytest