
name: Pytest_conduit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up -d

    - name: Sleep for 45 seconds
      run: sleep 45s
      shell: bash

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install seleniumbase

      run: pip install seleniumbase


    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    

    - name: Test with pytest
      run: |
        pytest
      
       
    